name: Terraform CI/CD

on:
  push:
    branches:
      - dev
      - main
  pull_request:

permissions:
  id-token: write
  contents: read

jobs:
  # 🔵 DEV JOB
  terraform-dev:
    if: github.ref == 'refs/heads/dev'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
      - name: Configure AWS Credentials Dev
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::393078901209:role/github-terraform-dev-role
          aws-region: us-east-1
      - name: Terraform Init
        run: terraform init
      - name: Terraform Plan
        run: terraform plan
      - name: Terraform Apply Dev
        run: terraform apply -auto-approve

  # 🔴 PROD JOB
  terraform-prod:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment: prod  # ✅ CORRECT PLACE
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
      - name: Configure AWS Credentials Prod
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::393078901209:role/github-terraform-prod-role
          aws-region: us-east-1
      - name: Terraform Init
        run: terraform init
      - name: Terraform Plan
        run: terraform plan
      - name: Terraform Apply Prod
        run: terraform apply -auto-approve

